name: fish-environment
channels:
  - conda-forge
dependencies:
  - python=3.7.9
  - numpy=1.18.5
  - torch==1.6.0
  - torchvision==0.7.0
  - fastai==2.0.10
  - pip
  - pip:
    - streamlit==0.66.0    
    - pillow==7.2.0
    - json5==0.9.5
    - jsonpickle==1.4.1
    - pickleshare==0.7.5    
