name: fish-environment
channels:
  - conda-forge
dependencies:
  - python=3.7.9
  - numpy=1.18.5
  - pip
  - pip:
    - jupyter-server-proxy
    - streamlit==0.66.0    
    - pillow==7.2.0
    - json5==0.9.5
    - jsonpickle==1.4.1
    - pickleshare==0.7.5    
    - torch @ https://download.pytorch.org/whl/cpu/torch-1.6.0%2Bcpu-cp37-cp37m-linux_x86_64.whl
    - torchvision @ https://download.pytorch.org/whl/cpu/torchvision-0.7.0%2Bcpu-cp37-cp37m-linux_x86_64.whl
    - fastai==2.0.10
