name: dl
channels:
  - conda
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.9
  - pip
  - jupyter-server-proxy
  - pip:
    - torch==1.7.1
    - torchvision==0.8.2
    - streamlit==0.66.0          
    - fastai==2.0.10 
