name: fish_env
channels:
  - conda-forge
dependencies:
  - python=3.7.9
  - numpy=1.18.5
  - pip:
    - streamlit==0.66.0    
    - aiohttp==3.6.2            # via jupyter-server-proxy
    - altair==4.1.0             # via streamlit
    - argon2-cffi==20.1.0       # via notebook
    - astor==0.8.1              # via streamlit
    - async-generator==1.10     # via nbclient
    - async-timeout==3.0.1      # via aiohttp
    - attrs==20.2.0             # via aiohttp, jsonschema
    - backcall==0.2.0           # via ipython
    - base58==2.0.1             # via streamlit
    - bleach==3.1.5             # via nbconvert
    - blinker==1.4              # via streamlit
    - blis==0.4.1               # via spacy, thinc
    - boto3==1.14.60            # via streamlit
    - botocore==1.17.60         # via boto3, s3transfer, streamlit
    - cachetools==4.1.1         # via streamlit
    - catalogue==1.0.0          # via spacy, thinc
    - certifi==2020.6.20        # via matplotlib, requests
    - cffi==1.14.2              # via argon2-cffi
    - chardet==3.0.4            # via aiohttp, requests
    - click==7.1.2              # via streamlit
    - cycler==0.10.0            # via matplotlib
    - cymem==2.0.3              # via preshed, spacy, thinc
    - decorator==4.4.2          # via ipython, validators
    - defusedxml==0.6.0         # via nbconvert
    - docutils==0.15.2          # via botocore
    - entrypoints==0.3          # via altair, nbconvert
    - enum-compat==0.0.3        # via streamlit
    - fastai==2.0.10            # via -r -
    - fastcore==1.0.9           # via fastai
    - fastprogress==1.0.0       # via fastai
    - future==0.18.2            # via torch
    - idna==2.10                # via requests, yarl
    - importlib-metadata==1.7.0  # via catalogue, jsonschema
    - ipykernel==5.3.4          # via ipywidgets, notebook, pydeck
    - ipython-genutils==0.2.0   # via nbformat, notebook, traitlets
    - ipython==7.18.1           # via ipykernel, ipywidgets
    - ipywidgets==7.5.1         # via pydeck
    - jedi==0.17.2              # via ipython
    - jinja2==2.11.2            # via altair, nbconvert, notebook, pydeck
    - jmespath==0.10.0          # via boto3, botocore
    - joblib==0.16.0            # via scikit-learn
    - jsonschema==3.2.0         # via altair, nbformat
    - jupyter-client==6.1.7     # via ipykernel, nbclient, notebook
    - jupyter-core==4.6.3       # via jupyter-client, nbconvert, nbformat, notebook
    - jupyter-server-proxy==1.5.0  # via -r -
    - jupyterlab-pygments==0.1.1  # via nbconvert
    - kiwisolver==1.2.0         # via matplotlib
    - markupsafe==1.1.1         # via jinja2
    - matplotlib==3.3.1         # via fastai
    - mistune==0.8.4            # via nbconvert
    - multidict==4.7.6          # via aiohttp, yarl
    - murmurhash==1.0.2         # via preshed, spacy, thinc
    - nbclient==0.5.0           # via nbconvert
    - nbconvert==6.0.2          # via -r -, notebook
    - nbformat==5.0.7           # via ipywidgets, nbclient, nbconvert, notebook
    - nest-asyncio==1.4.0       # via nbclient
    - notebook==6.1.4           # via jupyter-server-proxy, widgetsnbextension
    - numpy==1.19.2             # via altair, blis, fastprogress, matplotlib, pandas, pyarrow, pydeck, scikit-learn, scipy, spacy, streamlit, thinc, torch, torchvision
    - packaging==20.4           # via bleach, fastai, fastcore, streamlit
    - pandas==1.1.2             # via altair, fastai, streamlit
    - pandocfilters==1.4.2      # via nbconvert
    - parso==0.7.1              # via jedi
    - pathtools==0.1.2          # via watchdog
    - pexpect==4.8.0            # via ipython
    - pickleshare==0.7.5        # via ipython
    - pillow==7.2.0             # via fastai, matplotlib, streamlit, torchvision
    - plac==1.1.3               # via spacy, thinc
    - preshed==3.0.2            # via spacy, thinc
    - prometheus-client==0.8.0  # via notebook
    - prompt-toolkit==3.0.7     # via ipython
    - protobuf==3.13.0          # via streamlit
    - ptyprocess==0.6.0         # via pexpect, terminado
    - pyarrow==1.0.1            # via streamlit
    - pycparser==2.20           # via cffi
    - pydeck==0.4.1             # via streamlit
    - pygments==2.7.0           # via ipython, jupyterlab-pygments, nbconvert
    - pyparsing==2.4.7          # via matplotlib, packaging
    - pyrsistent==0.17.3        # via jsonschema
    - python-dateutil==2.8.1    # via botocore, jupyter-client, matplotlib, pandas, streamlit
    - pytz==2020.1              # via pandas, tzlocal
    - pyyaml==5.3.1             # via fastai
    - pyzmq==19.0.2             # via jupyter-client, notebook
    - requests==2.24.0          # via fastai, spacy, streamlit
    - s3transfer==0.3.3         # via boto3
    - scikit-learn==0.23.2      # via fastai
    - scipy==1.5.2              # via fastai, scikit-learn
    - send2trash==1.5.0         # via notebook
    - simpervisor==0.3          # via jupyter-server-proxy
    - six==1.15.0               # via argon2-cffi, bleach, cycler, jsonschema, packaging, protobuf, python-dateutil, validators
    - spacy==2.3.2              # via fastai
    - srsly==1.0.2              # via spacy, thinc
    - streamlit==0.66.0         # via -r -
    - terminado==0.8.3          # via notebook
    - testpath==0.4.4           # via nbconvert
    - thinc==7.4.1              # via spacy
    - threadpoolctl==2.1.0      # via scikit-learn
    - toml==0.10.1              # via streamlit
    - toolz==0.10.0             # via altair
    - torch==1.6.0              # via fastai, torchvision
    - torchvision==0.7.0        # via fastai
    - tornado==6.0.4            # via ipykernel, jupyter-client, notebook, streamlit, terminado
    - tqdm==4.49.0              # via spacy, thinc
    - traitlets==5.0.4          # via ipykernel, ipython, ipywidgets, jupyter-client, jupyter-core, nbclient, nbconvert, nbformat, notebook, pydeck
    - typing-extensions==3.7.4.3  # via yarl
    - tzlocal==2.1              # via streamlit
    - urllib3==1.25.10          # via botocore, requests
    - validators==0.18.1        # via streamlit
    - wasabi==0.8.0             # via spacy, thinc
    - watchdog==0.10.3          # via streamlit
    - wcwidth==0.2.5            # via prompt-toolkit
    - webencodings==0.5.1       # via bleach
    - widgetsnbextension==3.5.1  # via ipywidgets
    - yarl==1.5.1               # via aiohttp
    - zipp==3.1.0               # via importlib-metadata
