name: dl
channels:
  - conda
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.9
  - pip
  - jupyter-server-proxy
  - pytorch 
  - torchvision
  - pip:
    - streamlit==0.66.0          
    - fastai==2.0.10 
