name: dl
channels:
  - conda
  - conda-forge
dependencies:
  - python=3.7.9
  - pip
  - jupyter-server-proxy
  - pytorch==1.7.1
  - torchvision==0.8.2  
  - pip:
    - streamlit==0.66.0          
    - fastai==2.0.10 
