name: dl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.9
  - pip
  - jupyter-server-proxy
  - torch==1.6.0              
  - torchvision==0.7.0        
  - fastai==2.0.10
  - pip:
    - streamlit
